<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <ContentTargetFolders>.</ContentTargetFolders>
        <Product>Slimsy</Product>
        <PackageId>Our.Umbraco.Slimsy</PackageId>
        <Title>Slimsy</Title>
        <Description>Effortless Responsive Images with Umbraco using LazySizes.js</Description>
        <PackageTags>umbraco plugin package images responsive umbraco-marketplace</PackageTags>
        <RootNamespace>Slimsy</RootNamespace>
        <FileVersion>0.0.0.0</FileVersion>
        <InformationalVersion>0.0.0</InformationalVersion>
		    <PackageIcon>slimsy.png</PackageIcon>
		    <PackageLicenseExpression>MIT</PackageLicenseExpression>
		    <Nullable>enable</Nullable>
		    <PackageProjectUrl>https://github.com/Jeavon/Slimsy</PackageProjectUrl>
		    <Authors>Jeavon Leopold, Marc Stöcker, William Phillips, Imran Haider</Authors>
		    <RepositoryUrl>https://github.com/Jeavon/Slimsy</RepositoryUrl>
		    <PackageReadmeFile>README.md</PackageReadmeFile>
        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
        <StaticWebAssetBasePath>App_Plugins/Slimsy</StaticWebAssetBasePath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Umbraco.Cms.Web.Common" Version="17.0.1" />
    </ItemGroup>

  <ItemGroup>
    <Content Include="buildTransitive\**" PackagePath="buildTransitive" />
  </ItemGroup>

  <ItemGroup>
      <None Remove="Scripts\lazysizes.min.js" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="Scripts\lazysizes.min.js">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="slimsy.png">
		 <Pack>True</Pack>
	   <PackagePath></PackagePath>
      </None>
    </ItemGroup>
</Project>
