name: Build and Package

env:
  PATH_TO_EXTENSION: "src/Slimsy"

  DOTNET_VERSION: '10'

on:
  workflow_dispatch:
    inputs:
      publish_to_nuget:
        description: 'Publish to nuget.org'
        required: false
        type: boolean
        default: false

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          filter: tree:0
      
      - name: Fetch all tags
        run: git fetch --force --tags
        
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: false
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            conventional-changelog-conventionalcommits

      - name: Echo the version
        run: |
          echo "New release version: '${{ steps.semantic.outputs.new_release_version }}'"
          echo "New release major: '${{ steps.semantic.outputs.new_release_major_version }}'"
          echo "New release minor: '${{ steps.semantic.outputs.new_release_minor_version }}'"
          echo "New release patch: '${{ steps.semantic.outputs.new_release_patch_version }}'"
          echo "Last release version: '${{ steps.semantic.outputs.last_release_version }}'"
          echo "New release published: '${{ steps.semantic.outputs.new_release_published }}'"
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 5
    env:
      MYGET_API_KEY: ${{ secrets.MYGET_API_KEY }}
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache NuGet
      id: nuget-packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: nuget-cache-${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj*') }}
        restore-keys: |
          nuget-cache-${{ runner.os }}-nuget-

    - name: Update Version Files
      run: .github/scripts/update-version-files.sh "${{ needs.setup.outputs.semver }}" "${{ env.PATH_TO_EXTENSION }}"   

    - name: Build slnx
      run: dotnet build ${{ github.workspace }}/*.slnx -c Release        

    - name: Pack NuGet Package
      working-directory: ${{ env.PATH_TO_EXTENSION }}
      run: dotnet pack --configuration Release /p:PackageVersion=${{ needs.setup.outputs.semver }}
    
    - name: Install Package Validation Tool
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      run: dotnet tool install -g dotnet-validate --prerelease
    
    - name: Validate NuGet Package
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      run: dotnet validate package local ${{ env.PATH_TO_EXTENSION }}/bin/Release/Our.Umbraco.Slimsy.*.nupkg
    
    - name: Create GitHub Release
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: .github/scripts/create-release-notes.sh "${{ needs.setup.outputs.semver }}" "Our.Umbraco.Slimsy" "https://nuget.pkg.github.com/Jeavon/index.json" "https://www.myget.org/F/umbraco-packages/api/v3/index.json"
    
    - name: Add GitHub Packages Source
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Jeavon/index.json"

    - name: Push NuGet Package
      if: ${{ needs.setup.outputs.new_release_published == 'true' }}
      run: dotnet nuget push "${{ env.PATH_TO_EXTENSION }}/bin/Release/Our.Umbraco.Slimsy.*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
    
    - name: Push MyGet Package
      if: needs.setup.outputs.new_release_published == 'true' && env.MYGET_API_KEY != ''
      run: dotnet nuget push "${{ env.PATH_TO_EXTENSION }}/bin/Release/Our.Umbraco.Slimsy.*.nupkg" --api-key ${{ env.MYGET_API_KEY }} --source https://www.myget.org/F/umbraco-packages/api/v2/package --skip-duplicate
      
    - name: Push to Nuget.org
      if: ${{ needs.setup.outputs.new_release_published == 'true' && github.event.inputs.publish_to_nuget == 'true' && startsWith(github.ref, 'refs/heads/main-') && !contains(needs.setup.outputs.semver, '-') }}
      run: dotnet nuget push "${{ env.PATH_TO_EXTENSION }}/bin/Release/Our.Umbraco.Slimsy.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    
    - name: Merge main branch to dev
      if: ${{ needs.setup.outputs.new_release_published == 'true' && startsWith(github.ref, 'refs/heads/main-') }}
      run: .github/scripts/merge-to-develop.sh "${{ needs.setup.outputs.semver }}"
      
